---

#
# Load vars depending on OS and so on...
#
- name: Ansible - include task init.yml
  include: init.yml
  static: true

#
# Packages
#
- name: Ansible - include task package.yml
  include: package.yml
  static: true


#
# Configuration start here
#
