---

- name: Package - Install EPEL
  package:
    name: epel-release
    state: present

- name: Package - Install Remi Repo
  package:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
