---

### BLOCK INCLUDE START
- set_fact:                                                             
    ansible_distro: "{{ ansible_distribution|lower|replace('\"', '') }}"

- include_vars: "{{ item }}"
  with_first_found:
    - files:                                                                    
      - "{{ ansible_distro }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
      - "{{ ansible_distro }}-{{ ansible_distribution_release }}.yml"           
      - "{{ ansible_distro }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
      - "{{ ansible_distro }}.yml"                                              
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "{{ ansible_distribution }}.yml"                                        
      - "{{ ansible_os_family }}.yml"                                           
      - "{{ ansible_os_family|lower }}.yml"                                     
      - "default.yml"                                                           
    - paths:                                                                    
      - ../vars                                                                 
  tags: ['always']

- name: Ansible - Call OS-specific tasks
  include: {{ ansible_os_family }}.yml
  tags: ['always']

### BLOCK INCLUDE END

- name: Package - Install php-fpm
  package: name={{ item }} state=present
  with_items: "{{ phpfpm_packages_base }}"
  tags: ['package']
