---

- name: Ansible - Call dynamic vars loading
  include: init.yml
  static: true

#
# Packages
#
- name: Package - Install packages
  include: package.yml
  static: true
  when: " done_pki_letsencrypt_packages|default(0) < 1"

- set_fact: done_pki_letsencrypt_packages=1

#
# Configuration
#

- name: Security - Request certificate
  include: request.yml
  static: true

