---

phpfpm_conf_base: /etc/php/fpm-php7.1
phpfpm_conf_file_main: "{{ phpfpm_conf_base }}/php-fpm.conf"

phpfpm_run_file: /run/php-fpm.pid

phpfpm_packages_base:
  - dev-lang/php

phpfpm_packages_gentoouse:
  # Core features
  - fpm
  - cli
  - opcache
  - threads
  - posix
  - pcntl
  # Compression
  - bzip2
  - zip
  - zlib
  - phar
  # main features
  - calendar
  - crypt
  - ftp
  - sockets
  - readline
  - session
  - curl
  - bcmath
  # Multibytes strings
  - unicode
  - mcrypt
  - mbstring
  - iconv
  # database
  - mysql
  - mysqli
  - pdo
  - sqlite
  - ldap
  # Format input output
  - json
  - xml
  - simplexml
  - soap
  - xmlreader
  - xmlwriter
  - xslt
  - inifile
  # Imaging
  - gd
  - exif

phpfpm_packages_extra:
#  - php-smbclient
  - dev-php/phalcon
  - dev-php/pecl-redis
#  - dev-php/pecl-uuid
  - dev-php/pecl-ssh2
#  - dev-php/tcpdf
#  - php-pecl-libsodium2
#  - php-pecl-inotify
#  - dev-php/pecl-gnupg
  - dev-php/pecl-geoip
#  - php-lz4

