---

phpfpm_packages_base:
  - dev-lang/php

phpfpm_packages_gentoouse:
  # Core features
  - fpm
  - cli
  - opcache
  - threads
  - posix
  - pcntl
  # Compression
  - bzip2
  - zip
  - zlib
  - phar
  # main features
  - calendar
  - crypt
  - ftp
  - sockets
  - readline
  - session
  - curl
  # Multibytes strings
  - unicode
  - mcrypt
  - mbstring
  - iconv
  # database
  - mysql
  - mysqli
  - pdo
  - sqlite
  # Format input output
  - json
  - xml
  - simplexml
  - soap
  - xmlreader
  - xmlwriter
  - xslt
  - inifile
  # Imaging
  - gd
  - exif

phpfpm_packages_extra:
#  - php-smbclient
#  - php-phalcon3
  - php-phpiredis
  - php-pecl-uuid
  - php-pecl-ssh2
#  - php-pecl-scrypt
#  - php-pecl-protobuf
#  - php-pecl-pdflib
#  - php-pecl-libsodium2
#  - php-pecl-inotify
#  - php-pecl-gnupg
  - php-pecl-geoip
#  - php-lz4
  - php-ldap
  - php-bcmath

